import Head from "next/head";
import React from "react";
import Navbar from "../Navbar/Navbar";
import Script from "next/script";
import { config, dom } from "@fortawesome/fontawesome-svg-core";

config.autoAddCss = false;

const Layout = ({ children, title, description }) => {
  return (
    <>
      <Head>
        <title>
          {title ? `${title} - Gaming Nation Plus` : "Gaming Nation Plus"}
        </title>
        <meta
          name="description"
          content={description || "Generated by create next app"}
        />
        <link rel="icon" href="/favicon.ico" />
        <style>{dom.css()}</style>
        <link
          rel="stylesheet"
          href="https://bootswatch.com/5/zephyr/bootstrap.css"
        ></link>
        <link
          rel="stylesheet"
          href="https://bootswatch.com/_vendor/font-awesome/css/font-awesome.min.css"
        ></link>
        <link
          rel="stylesheet"
          href="https://bootswatch.com/_vendor/prismjs/themes/prism-okaidia.css"
        ></link>
        <link
          rel="stylesheet"
          href="https://bootswatch.com/_assets/css/custom.min.css"
        ></link>
        <script
          async
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
          crossOrigin="anonymous"
        ></script>
        <script
          async
          src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"
          integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp"
          crossOrigin="anonymous"
        ></script>
        <script
          async
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"
          integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/"
          crossOrigin="anonymous"
        ></script>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Chakra+Petch&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Navbar />
      {children}
    </>
  );
};

export default Layout;
